x-php-base: &php-base
  logging:
    options:
      max-size: "50m"
      max-file: "5"
    driver: json-file
  user: "www-data:www-data"
  working_dir: /app
  volumes:
    - ${SRC_MOUNT_SOURCE:-.}:/app
    - ./${DOCKER_XDEBUG_CONFIG_FILE:-docker/php/conf.d/xdebug.ini.dist}:/usr/local/etc/php/conf.d/xdebug.ini
    - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    - ci-cache:/cache/ci-cache
  environment:
    PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=127.0.0.1}
    COMPOSER_AUTH: ${COMPOSER_AUTH:-}

x-php-build-args: &php-build-args
  PHP_ADDITIONAL_EXT: ${PHP_ADDITIONAL_EXT:-xdebug}

services:
  app:
    <<: *php-base
    build:
      context: ./docker/php/roadrunner
      dockerfile: ../Dockerfile
      target: app-rr
      args:
        <<: *php-build-args
    networks:
      - default
    ports:
      - "8001:8080"
    command: "rr serve -p -c .rr.dev.yaml"
    depends_on:
      - database
      - redis
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      PHP_IDE_CONFIG: "serverName=php-cli"
  cli:
    init: true
    <<: *php-base
    build:
      context: ./docker/php/cli
      dockerfile: ../Dockerfile
      target: app-cli
      args:
        <<: *php-build-args
    command: "tail -f /dev/null"
    networks:
      - default
  database:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - '25432:5432'
    environment:
      POSTGRES_DB: 'listener'
      POSTGRES_USER: 'listener'
      POSTGRES_PASSWORD: 'listener'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./var/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0.8-alpine
    volumes:
      - redis:/data
    ports:
      - "127.0.0.1:6479:6379"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=listener
      - RABBITMQ_DEFAULT_PASS=listener
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  database:
  redis:
  listener-mutagen-src-volume:
  ci-cache:

networks:
  default:
    driver: bridge
    ipam:
      driver: default

