# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Redis $redisDefault: '@snc_redis.default'
#            string $projectDir: '%kernel.project_dir%'
#            int $appId: '%env(TELEGRAM_API_ID)%'
#            int $chatId: '%env(TELEGRAM_CHAT_ID)%'
#            string $appHash: '%env(TELEGRAM_API_HASH)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

#    App\Command\Account\AccountLoadMarketsCommand:
#        arguments:
#            - '@snc_redis.default'

    _instanceof:
        App\Processor\ProcessorInterface:
            tags: [ 'processor' ]

    App\Processor\ProcessorFactory:
        arguments:
            - !tagged_iterator processor

